dist: trusty
os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "12.13.0"
#cache:
#  directories:
#    - node
#    - node_modules
env:
  global:
    - NODE_VERSION=12.13.1
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - NG_CLI_ANALYTICS="false"
before_install:
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get update
  - sudo apt-get install -y openjdk-8-jdk
  - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
  - java -version
  - sudo apt-get install maven
  - mvn -version
#  - sudo /etc/init.d/mysql stop
#  - sudo /etc/init.d/postgresql stop
install: true
script:
  -  sudo mvn clean install
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
