os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "10.16.3"
cache:
  directories:
    - node
    - node_modules
env:
  global:
    - NODE_VERSION=10.16.3
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - NG_CLI_ANALYTICS="false"
before_install:
  - echo '*** Using OpenJDK 11 by default'
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get update
  - sudo apt-get install -y openjdk-11-jdk
  - sudo update-java-alternatives -s java-1.11.0-openjdk-amd64
  - java -version
#  - sudo /etc/init.d/mysql stop
#  - sudo /etc/init.d/postgresql stop
install:
script:
  -  mvn clean install
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
