version: '2'
services:
  sharelocserver-app:
    image: sharelocserver
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://sharelocserver-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=ShareLocServer
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - KAFKA_CONSUMER_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - KAFKA_CONSUMER_VALUE_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_GROUP_ID=share-loc-server
      - KAFKA_CONSUMER_AUTO_OFFSET_RESET=earliest
      - KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_PRODUCER_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - KAFKA_PRODUCER_VALUE_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
    ports:
      - 8080:8080
  sharelocserver-mongodb:
    extends:
      file: mongodb.yml
      service: sharelocserver-mongodb
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
