version: '2'
services:
    shareloc_server-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        command: mongos --configdb shareloc_server-mongodb-config
    shareloc_server-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    shareloc_server-mongodb-config:
        image: mongo:3.6.3
        container_name: shareloc_server-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
